In [44]:
# Trabalho 1 de Transmissão de Energia
# Baseado em Kersting - Distribution System Modeling and Analysis (p. 92-95)
#
# Exemplo 4.1 

import numpy as np
from numpy.linalg import inv
from IPython.display import display

In [2]:
# Dados do enunciado

GMR_f = 0.0244 # [ft.]
Resistance_f = 0.306 # [ohms/mile]

GMR_n = 0.00814
Resistance_n = 0.5920

# D [ft.]
d_ab = 2.5
d_bc = 4.5
d_ca = 7.0
d_an = 5.6569
d_bn = 4.272
d_cn = 5.0

In [3]:
D = np.array([[1, d_ab, d_ca, d_an],
             [d_ab, 1, d_bc, d_bn],
             [d_ca, d_bc, 1, d_cn],
             [d_an, d_bn, d_cn, 1]])

In [4]:
#D = D*0.000189394 # ft. to miles

In [11]:
Z = np.zeros(shape=(4,4),dtype=np.complex_)
display(Z)

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [15]:
for (i,j), value in np.ndenumerate(D): # loop 2 dimensões para calcular Z^
    if i==j:
        if i==3: # iterando para o neutro
            Z[i,j] = Resistance_n + 0.09530 + (0.12134j*(np.log(1./GMR_n)+7.93402))
        else:
            Z[i,j] = Resistance_f + 0.09530 + (0.12134j*(np.log(1./GMR_f)+7.93402))
    else:
        Z[i,j] = 0.09530 + (0.12134j*(np.log(1./D[i,j])+7.93402))

In [16]:
display(Z)

array([[ 0.4013+1.4132703j ,  0.0953+0.85153127j,  0.0953+0.72659725j,
         0.0953+0.75244681j],
       [ 0.0953+0.85153127j,  0.4013+1.4132703j ,  0.0953+0.78020924j,
         0.0953+0.78651834j],
       [ 0.0953+0.72659725j,  0.0953+0.78020924j,  0.4013+1.4132703j ,
         0.0953+0.76742479j],
       [ 0.0953+0.75244681j,  0.0953+0.78651834j,  0.0953+0.76742479j,
         0.6873+1.54647649j]])

In [18]:
Zij = Z[0:3,0:3]
display(Zij)

array([[ 0.4013+1.4132703j ,  0.0953+0.85153127j,  0.0953+0.72659725j],
       [ 0.0953+0.85153127j,  0.4013+1.4132703j ,  0.0953+0.78020924j],
       [ 0.0953+0.72659725j,  0.0953+0.78020924j,  0.4013+1.4132703j ]])

In [19]:
Zin = Z[3,0:3]
display(Zin)

array([ 0.0953+0.75244681j,  0.0953+0.78651834j,  0.0953+0.76742479j])

In [20]:
Znn = Z[3,3]
display(Znn)

(0.68730000000000002+1.5464764919087395j)

In [21]:
Znj = Z[0:3,3]
display(Znj)

array([ 0.0953+0.75244681j,  0.0953+0.78651834j,  0.0953+0.76742479j])

In [27]:
# Kron reduction (p. 94)
Zabc = Zij - (np.transpose(Zin) * (1./Znn) * Znj)
display(Zabc)

array([[ 0.45755083+1.07803538j,  0.16062762+0.4864243j ,
         0.15547239+0.37838489j],
       [ 0.15155083+0.51629636j,  0.46662762+1.04816333j,
         0.15547239+0.43199687j],
       [ 0.15155083+0.39136234j,  0.16062762+0.41510227j,
         0.46147239+1.06505793j]])

In [58]:
# a_s = 1|_120

a_s = np.cos(120 * np.pi / 180)*1 + np.sin(120 * np.pi / 180)*1.j 

A_s = np.array([[1,      1,           1],
                [1,    a_s**2,      a_s],
                [1,     a_s,     a_s**2]])
display(A_s)
display(inv(A_s))

array([[ 1.0+0.j       ,  1.0+0.j       ,  1.0+0.j       ],
       [ 1.0+0.j       , -0.5-0.8660254j, -0.5+0.8660254j],
       [ 1.0+0.j       , -0.5+0.8660254j, -0.5-0.8660254j]])

array([[ 0.33333333 -3.20493781e-17j,  0.33333333 +0.00000000e+00j,
         0.33333333 +0.00000000e+00j],
       [ 0.33333333 -0.00000000e+00j, -0.16666667 +2.88675135e-01j,
        -0.16666667 -2.88675135e-01j],
       [ 0.33333333 +3.20493781e-17j, -0.16666667 -2.88675135e-01j,
        -0.16666667 +2.88675135e-01j]])

## (Certo até aqui)
Zabc como deve ser. Problemas com a operação com Z_012... Talvez erros na multiplicação com inversa? Testar.

In [59]:
Z_012 = inv(A_s) * Zabc * A_s
display(Z_012)

array([[ 0.15251694+0.35934513j,  0.05354254+0.16214143j,
         0.05182413+0.1261283j ],
       [ 0.05051694+0.17209879j,  0.15554254+0.34938778j,
         0.05182413+0.14399896j],
       [ 0.05051694+0.13045411j,  0.05354254+0.13836742j,
         0.15382413+0.35501931j]])