In [185]:
# Trabalho 1 de Transmissão de Energia
# Baseado em Kersting - Distribution System Modeling and Analysis (p. 92-95)
#
# Exemplo 4.1 

import numpy as np

In [186]:
# Dados do enunciado

GMR_f = 0.0244 # [ft.]
Resistance_f = 0.306 # [ohms/mile]

GMR_n = 0.00814
Resistance_n = 0.5920

# D [ft.]
d_ab = 2.5
d_bc = 4.5
d_ca = 7.0
d_an = 5.6569
d_bn = 4.272
d_cn = 5.0

In [187]:
D = np.array([[1, d_ab, d_ca, d_an],
             [d_ab, 1, d_bc, d_bn],
             [d_ca, d_bc, 1, d_cn],
             [d_an, d_bn, d_cn, 1]])

In [188]:
#D = D*0.000189394 # ft. to miles

In [189]:
Z = np.zeros(shape=(4,4),dtype=np.complex_)
Z[0,1] = 3.+2.j

In [190]:
np.log(1)

0.0

In [191]:
Zab=0.09530 + 0.306 + (0.12134j*(np.log(1./GMR_f)+7.93402))
Zab

(0.4013+1.413270295078513j)

In [192]:
Zab=0.09530 + (0.12134j*(np.log(1./D[0,1])+7.93402))
Zab

(0.0953+0.8515312693943901j)

In [193]:
for (i,j), value in np.ndenumerate(D): # loop 2 dimensões para calcular Z^
    if i==j:
        if i==3: # iterando para o neutro
            Z[i,j] = Resistance_n + 0.09530 + (0.12134j*(np.log(1./GMR_n)+7.93402))
        else:
            Z[i,j] = Resistance_f + 0.09530 + (0.12134j*(np.log(1./GMR_f)+7.93402))
    else:
        Z[i,j] = 0.09530 + (0.12134j*(np.log(1./D[i,j])+7.93402))

In [194]:
for row in Z:
    print row

[ 0.4013+1.4132703j   0.0953+0.85153127j  0.0953+0.72659725j
  0.0953+0.75244681j]
[ 0.0953+0.85153127j  0.4013+1.4132703j   0.0953+0.78020924j
  0.0953+0.78651834j]
[ 0.0953+0.72659725j  0.0953+0.78020924j  0.4013+1.4132703j
  0.0953+0.76742479j]
[ 0.0953+0.75244681j  0.0953+0.78651834j  0.0953+0.76742479j
  0.6873+1.54647649j]


In [195]:
Zij = Z[0:3,0:3]
Zij

array([[ 0.4013+1.4132703j ,  0.0953+0.85153127j,  0.0953+0.72659725j],
       [ 0.0953+0.85153127j,  0.4013+1.4132703j ,  0.0953+0.78020924j],
       [ 0.0953+0.72659725j,  0.0953+0.78020924j,  0.4013+1.4132703j ]])

In [196]:
Zin = Z[3,0:3]
Zin

array([ 0.0953+0.75244681j,  0.0953+0.78651834j,  0.0953+0.76742479j])

In [197]:
Znn = Z[3,3]
Znn

(0.68730000000000002+1.5464764919087395j)

In [198]:
Znj = Z[0:3,3]
Znj

array([ 0.0953+0.75244681j,  0.0953+0.78651834j,  0.0953+0.76742479j])

In [212]:
1./(Znn)

(0.239981494502049-0.53997634183114385j)

In [211]:
Zabc = Zij - np.dot(np.transpose(Zin) , np.dot(1./(Znn) , Znj))
Zabc

array([[ 0.58305084+0.36471605j,  0.27705084-0.19702297j,
         0.27705084-0.32195699j],
       [ 0.27705084-0.19702297j,  0.58305084+0.36471605j,
         0.27705084-0.26834501j],
       [ 0.27705084-0.32195699j,  0.27705084-0.26834501j,
         0.58305084+0.36471605j]])

In [203]:
a = np.dot(np.conj(Znn) , Znj)

In [204]:
np.dot(np.transpose(Zin) , a)

(-0.52052911772233879+3.003028768931761j)